#!/usr/bin/env python3
"""
Generate the LaTeX result tables of the thesis from the fit reports.

    python3 make_thesis_tables.py            # DE reports (default)
    python3 make_thesis_tables.py --stage LM # LM reports

Reads  fits/fit_{v}_floor20MeV_{STAGE}_{dataset}.txt
Writes thesis/tables/{chi2,params_*,spectrum_*,bstar}.tex

Every table is a self-contained LaTeX float with its own \\label, so the
chapter text never has to be edited when a fit is repeated.
"""
import argparse, glob, math, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
FITS = os.path.join(HERE, "fits")
OUT  = os.path.join(HERE, "thesis", "tables")

VARIANTS = ["v1", "v2", "v3"]
DATASETS = {"setA": "charmonium_states_1",
            "setB": "charmonium_states_2",
            "combined": "combined"}

# spectroscopic label -> (particle name, data set)
NAMES = {
    "1 ^1S_0": r"$\eta_c(1S)$",      "1 ^3S_1": r"$J/\psi$",
    "1 ^3P_0": r"$\chi_{c0}(1P)$",   "1 ^3P_1": r"$\chi_{c1}(1P)$",
    "1 ^1P_1": r"$h_c(1P)$",         "1 ^3P_2": r"$\chi_{c2}(1P)$",
    "2 ^1S_0": r"$\eta_c(2S)$",      "2 ^3S_1": r"$\psi(2S)$",
    "1 ^3D_1": r"$\psi(3770)$",      "1 ^3D_2": r"$\psi_2(3823)$",
    "2 ^3P_1": r"$X(3872)$",         "2 ^3P_2": r"$\chi_{c2}(3930)$",
    "3 ^3S_1": r"$\psi(4040)$",      "3 ^3P_1": r"$X(4140)$",
    "4 ^3S_1": r"$Y(4230)$",         "4 ^3P_1": r"$X(4274)$",
}
PARAM_ROWS = [
    ("bar_V_v", r"$\bar V_v$ [\si{\GeV}]"),
    ("alpha",   r"$\alpha$"),
    ("d",       r"$d$ (or $d_v$) [\si{\GeV^{-1}}]"),
    ("bar_V_s", r"$\bar V_s$ [\si{\GeV}]"),
    ("r_s",     r"$r_s$ [\si{\GeV^{-1}}]"),
    ("d_s",     r"$d_s$ [\si{\GeV^{-1}}]"),
]

def parse(path):
    """Return dict with params, chi2, dof, chi2dof, states, bstar."""
    txt = open(path).read()
    out = {"params": {}, "states": [], "bstar": []}

    m = re.search(r"^\s+chi\^2\s+=\s+([\d.]+)", txt, re.M)
    out["chi2"] = float(m.group(1)) if m else None
    m = re.search(r"degrees of freedom\s+=\s+(\d+)", txt)
    out["dof"] = int(m.group(1)) if m else None
    m = re.search(r"reduced chi\^2\s+\(chi\^2/dof\)=\s+([\d.]+)", txt)
    out["chi2dof"] = float(m.group(1)) if m else None

    blk = re.search(r"Best-fit potential parameters\n-+\n(.*?)\n\n", txt, re.S)
    if blk:
        for line in blk.group(1).splitlines():
            mm = re.match(r"\s+(\w+)\s+([+-][\d.]+)\s+\+/-\s+([\d.]+)", line)
            if mm:
                name = mm.group(1)
                if name == "d_v":
                    name = "d"
                out["params"][name] = (float(mm.group(2)), float(mm.group(3)))

    blk = re.search(r"Per-state predictions.*?\n-+\n.*?\n(.*?)\n\n", txt, re.S)
    if blk:
        for line in blk.group(1).splitlines():
            mm = re.match(r"\s+(\d \^\dS_\d|\d \^\d[SPDF]_\d)\s+([\d.]+)\s+([\d.]+)"
                          r"\s+([\d.]+)\s+([+-][\d.]+)\s+([+-][\d.]+)", line)
            if mm:
                out["states"].append(dict(
                    label=mm.group(1), pred=float(mm.group(2)),
                    exp=float(mm.group(3)), sig=float(mm.group(4)),
                    delta=float(mm.group(5)), pull=float(mm.group(6))))

    blk = re.search(r"Variational HO scale.*?\n-+\n.*?\n(.*?)\n\n", txt, re.S)
    if blk:
        for line in blk.group(1).splitlines():
            mm = re.match(r"\s+\((\d), (\d), (\d)\)\s+([\d.]+)\s+([\d.]+)", line)
            if mm:
                out["bstar"].append((int(mm.group(1)), int(mm.group(2)),
                                     int(mm.group(3)), float(mm.group(4)),
                                     float(mm.group(5))))
    return out

def tex_state(label):
    """'1 ^3P_1' -> \state{1}{3}{P}{1}"""
    m = re.match(r"(\d) \^(\d)([SPDF])_(\d)", label)
    return r"$\state{%s}{%s}{%s}{%s}$" % m.groups()

def header(stage, src):
    return (f"% Generated by make_thesis_tables.py from the {stage} fit reports.\n"
            f"% Source: {src}\n% Do not edit by hand -- rerun the script instead.\n")

def write(name, body):
    with open(os.path.join(OUT, name), "w") as f:
        f.write(body)
    print("  wrote tables/" + name)

# ---------------------------------------------------------------------------
#  Experimental values are taken from the CSVs, not from the fit reports, so
#  that updating the data (e.g. a new PDG edition) does not require refitting.
#  Predictions come from the reports; Delta, pull and chi^2 are recomputed.
# ---------------------------------------------------------------------------
SIGMA_FLOOR = 20.0        # MeV, must match --sigma-floor of the fits
_LMAP = {"S": 0, "P": 1, "D": 2, "F": 3}

def load_csv_exp():
    """(n, L, S, J) -> (exp, sigma) from charmonium_states_*.csv"""
    out = {}
    for fn in sorted(glob.glob(os.path.join(HERE, "charmonium_states_?.csv"))):
        with open(fn) as fh:
            next(fh)
            for line in fh:
                if not line.strip():
                    continue
                n, J, L, S, E, sig = line.split(",")
                out[(int(n), int(L), int(S), int(J))] = (float(E), float(sig))
    return out

def label_key(label):
    m = re.match(r"(\d) \^(\d)([SPDF])_(\d)", label)
    n, mult, Ls, J = int(m.group(1)), int(m.group(2)), m.group(3), int(m.group(4))
    return (n, _LMAP[Ls], (mult - 1) // 2, J)

def apply_csv_exp(rep, exp_table):
    """Overwrite exp/sigma with the CSV values and recompute Delta, pull, chi^2."""
    chi2 = 0.0
    for st in rep["states"]:
        key = label_key(st["label"])
        if key not in exp_table:
            continue
        E, sig = exp_table[key]
        st["exp"], st["sig"] = E, sig
        st["delta"] = st["pred"] - E
        st["pull"] = st["delta"] / math.sqrt(sig * sig + SIGMA_FLOOR ** 2)
        chi2 += st["pull"] ** 2
    if rep["states"]:
        rep["chi2"] = chi2
        if rep.get("dof"):
            rep["chi2dof"] = chi2 / rep["dof"]
    return rep

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stage", default="DE", choices=["DE", "LM"])
    args = ap.parse_args()
    stage = args.stage

    R = {}
    EXP = load_csv_exp()
    missing = []
    for v in VARIANTS:
        for key, ds in DATASETS.items():
            p = os.path.join(FITS, f"fit_{v}_floor20MeV_{stage}_{ds}.txt")
            if os.path.exists(p):
                R[(v, key)] = apply_csv_exp(parse(p), EXP)
            else:
                missing.append((v, key))
    if missing:
        print("  MISSING reports:", ", ".join(f"{v}/{k}" for v, k in missing))

    def cell(v, key, fmt, *keys):
        r = R.get((v, key))
        if r is None:
            return r"---"
        return fmt(r, *keys)

    stagetxt = ("differential evolution + Levenberg--Marquardt + variational polish"
                if stage == "DE" else
                "Levenberg--Marquardt + variational polish")
    note = ("" if not missing else
            r" The \texttt{" + stage + r"} run has no report for " +
            ", ".join(f"{v}/{k}" for v, k in missing) +
            r"; those entries are marked ---.")

    # ---------------- chi^2 ------------------------------------------------
    rows = []
    for v, npar in zip(VARIANTS, ["6p", "5p", "4p"]):
        c = []
        for key in ["setA", "setB", "combined"]:
            r = R.get((v, key))
            c += ([f"{r['chi2']:.2f}", f"{r['chi2dof']:.2f}"] if r else ["---", "---"])
        rows.append(f"{v} ({npar}) & " + " & ".join(c) + r" \\")
    write("chi2.tex", header(stage, "fit_*_" + stage + "_*.txt") + r"""
\begin{table}[H]\centering
\caption{Statistical quality of the nine fits (%s, $\nst=30$,
$\sigma_{\text{floor}}=\SI{20}{\MeV}$).%s}
\label{tab:chi2}
\begin{tabular}{lcccccc}
\toprule
& \multicolumn{2}{c}{Set A (8 states)} & \multicolumn{2}{c}{Set B (8 states)} & \multicolumn{2}{c}{Combined (16)}\\
\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}
Variant & $\chi^{2}$ & $\chi^{2}/\text{dof}$ & $\chi^{2}$ & $\chi^{2}/\text{dof}$ & $\chi^{2}$ & $\chi^{2}/\text{dof}$\\
\midrule
%s
\bottomrule
\end{tabular}
\end{table}
""" % (stagetxt, note, "\n".join(rows)))

    # ---------------- parameters ------------------------------------------
    titles = {"setA": "set~A (8 low-lying states)",
              "setB": "set~B (8 higher states)",
              "combined": "the combined set (16 states)"}
    for key in ["setA", "setB", "combined"]:
        rows = []
        for pname, plabel in PARAM_ROWS:
            cells = []
            for v in VARIANTS:
                r = R.get((v, key))
                if r is None:
                    cells.append("---")
                elif pname in r["params"]:
                    val, err = r["params"][pname]
                    cells.append(f"${val:.3f}\\pm{err:.3f}$")
                else:
                    cells.append("---")
            if set(cells) == {"---"}:
                continue
            rows.append(f"{plabel} & " + " & ".join(cells) + r" \\")
        write(f"params_{key}.tex", header(stage, "fit_*_" + stage + f"_{DATASETS[key]}.txt") + r"""
\begin{table}[H]\centering
\caption{Best-fit parameters for %s, with $1\sigma$ uncertainties from the
covariance matrix. In v3 $\bar V_v$ is not free but fixed by
$\bar V_v=2m_c-\bar V_s$.}
\label{tab:params-%s}
\begin{tabular}{lccc}
\toprule
Parameter & v1 (6 par.) & v2 (5 par.) & v3 (4 par.)\\
\midrule
%s
\bottomrule
\end{tabular}
\end{table}
""" % (titles[key], key, "\n".join(rows)))

    # ---------------- spectra ---------------------------------------------
    for key in ["setA", "setB", "combined"]:
        ref = None
        for v in VARIANTS:
            if (v, key) in R:
                ref = R[(v, key)]
                break
        if ref is None:
            continue
        rows = []
        for i, st in enumerate(ref["states"]):
            cells = []
            for v in VARIANTS:
                r = R.get((v, key))
                if r is None or i >= len(r["states"]):
                    cells.append("---")
                else:
                    s = r["states"][i]
                    cells.append(f"${s['pred']:.1f}\\;({s['delta']:+.1f})$")
            rows.append(NAMES.get(st["label"], st["label"]) + " & " +
                        tex_state(st["label"]) + " & " +
                        f"{st['exp']:.2f} & {st['sig']:.3f} & " +
                        " & ".join(cells) + r" \\")
        write(f"spectrum_{key}.tex", header(stage, "fit_*_" + stage + f"_{DATASETS[key]}.txt") + r"""
\begin{table}[H]\centering
\caption{Predicted masses for %s, in \si{\MeV}, with
$\Delta=E^{\text{th}}-E^{\text{exp}}$ in parentheses.%s}
\label{tab:spectrum-%s}
\small
\begin{tabular}{llcccccc}
\toprule
State & Assignment & $E^{\text{exp}}$ & $\sigma_{\text{exp}}$ & v1 & v2 & v3\\
\midrule
%s
\bottomrule
\end{tabular}
\end{table}
""" % (titles[key], note, key, "\n".join(rows)))

    # ---------------- b* ---------------------------------------------------
    for v in ["v3", "v2", "v1"]:
        r = R.get((v, "combined"))
        if r and r["bstar"]:
            rows = [f"$({L},{S},{J})$ & {b:.3f} & {fm:.3f}" + r" \\"
                    for L, S, J, b, fm in r["bstar"]]
            write("bstar.tex", header(stage, f"fit_{v}_floor20MeV_{stage}_combined.txt") + r"""
\begin{table}[H]\centering
\caption{Optimal variational oscillator scale $\bstar(L,S,J)$, variant~%s,
combined fit ($\hbar c\simeq\SI{0.1973}{\GeV\,fm}$).}
\label{tab:bstar}
\begin{tabular}{lcc}
\toprule
Channel $(L,S,J)$ & $\bstar$ [\si{\GeV^{-1}}] & $\bstar$ [fm]\\
\midrule
%s
\bottomrule
\end{tabular}
\end{table}
""" % (v, "\n".join(rows)))
            break

    # ---------------- splittings ------------------------------------------
    SPLIT = [
        (r"$\mathrm{HF}(1S)=M(J/\psi)-M(\eta_c)$",            "1 ^3S_1", "1 ^1S_0"),
        (r"$\mathrm{HF}(2S)=M(\psi(2S))-M(\eta_c(2S))$",      "2 ^3S_1", "2 ^1S_0"),
        (r"$M(\chi_{c2})-M(\chi_{c0})$",                      "1 ^3P_2", "1 ^3P_0"),
        (r"$M(\chi_{c1})-M(\chi_{c0})$",                      "1 ^3P_1", "1 ^3P_0"),
        (r"$M(h_c)-M(\chi_{c1})$",                            "1 ^1P_1", "1 ^3P_1"),
    ]
    CENTROID = (r"$M(h_c)-\langle M(\chi_{cJ})\rangle$",
                "1 ^1P_1", [("1 ^3P_0", 1/9.), ("1 ^3P_1", 3/9.), ("1 ^3P_2", 5/9.)])

    def spl_table(key, tag, caption):
        ref = None
        for v in VARIANTS:
            if (v, key) in R:
                ref = R[(v, key)]
        if ref is None:
            return
        exp = {s["label"]: s["exp"] for s in ref["states"]}
        sig = {s["label"]: s["sig"] for s in ref["states"]}
        rows = []
        for label, a, b in SPLIT:
            if a not in exp or b not in exp:
                continue
            ds = math.hypot(sig.get(a, 0.0), sig.get(b, 0.0))
            cells = [f"${exp[a]-exp[b]:+.2f}\\pm{ds:.2f}$"]
            for v in VARIANTS:
                r = R.get((v, key))
                if r is None:
                    cells.append("---"); continue
                pr = {s["label"]: s["pred"] for s in r["states"]}
                cells.append(f"{pr[a]-pr[b]:+.1f}" if a in pr and b in pr else "---")
            rows.append(label + " & " + " & ".join(cells) + r" \\")
        label, a, ws = CENTROID
        if a in exp and all(w[0] in exp for w in ws):
            dcog = math.sqrt(sum((w * sig.get(k, 0.0)) ** 2 for k, w in ws))
            ds = math.hypot(sig.get(a, 0.0), dcog)
            _c = exp[a] - sum(w * exp[k] for k, w in ws)
            _cs = f"{_c:+.2f}" if abs(_c) >= 0.005 else "0.00"
            cells = [f"${_cs}\\pm{ds:.2f}$"]
            for v in VARIANTS:
                r = R.get((v, key))
                if r is None:
                    cells.append("---"); continue
                pr = {s["label"]: s["pred"] for s in r["states"]}
                cells.append(f"{pr[a]-sum(w*pr[k] for k, w in ws):+.1f}"
                             if a in pr and all(w[0] in pr for w in ws) else "---")
            rows.append(label + " & " + " & ".join(cells) + r" \\")
        if not rows:
            return
        write(f"splittings_{key}.tex", header(stage, "fit_*_" + stage + f"_{DATASETS[key]}.txt") + r"""
\begin{table}[H]\centering
\caption{%s All entries in \si{\MeV}; the experimental column carries the
uncertainty propagated in quadrature from Table~\ref{tab:data}. The last row
uses the spin-averaged triplet mass
$\langle M(\chi_{cJ})\rangle=[M(\chi_{c0})+3M(\chi_{c1})+5M(\chi_{c2})]/9$,
in which the spin--orbit and tensor contributions cancel exactly
($\sum_J(2J{+}1)\kLS=\sum_J(2J{+}1)\TLL=0$). A negative
$M(h_c)-M(\chi_{c1})$ signals the inversion discussed in
Sect.~\ref{sec:hc-inversion}; experimentally it is positive.}
\label{tab:splittings-%s}
\begin{tabular}{lcccc}
\toprule
Splitting & Experiment & v1 & v2 & v3\\
\midrule
%s
\bottomrule
\end{tabular}
\end{table}
""" % (caption, tag, "\n".join(rows)))

    spl_table("combined", "combined",
              "Fine and hyperfine splittings from the combined fit.")
    spl_table("setA", "setA",
              "Fine and hyperfine splittings from the fit to set~A.")

    print("done.")

if __name__ == "__main__":
    main()
