"""
Figure for Sect. 7.2: the fitted interactions of the three variants.

  (a) V_v and V_s      (b) V_L and V_U
  (c) A_L and A_U      (d) the tensor kernel -V_v V_s A_L^2 A_U

Encoding: colour + dash style = variant; line thickness = which of the two
quantities in the panel (thick = the first named, thin = the second).  Each
curve family also carries a direct label inside its panel, so nothing depends
on "upper"/"lower", which is fragile where the two families cross or merge.
The variant key is a single shared legend above the panels.

Parameters are the combined-fit (DE) values of Chapter 8.
Emits thesis/figures/potentials.tex.
"""
import numpy as np
import meson_potential as v1
import meson_potential_v2 as v2
import meson_potential_v3 as v3

M_Q = 1.275
OUT = "potentials.tex"

# combined-fit DE parameters
P1 = dict(bar_V_v=1.76679, alpha=2.41160, d_v=2.22520,
          bar_V_s=0.73392, r_s=5.96728, d_s=7.79992)
P2 = dict(bar_V_v=1.92410, alpha=4.11051, d=3.28334,
          bar_V_s=0.86668, r_s=1.43734)
P3 = dict(alpha=1.90818, d=1.89164, bar_V_s=0.81805, r_s=9.28005, m_q=M_Q)

# E_T of the 1 3S1 level in each combined fit (GeV), from the reports
ET = {"v1": 3.12657, "v2": 3.08513, "v3": 3.13476}

r = np.linspace(0.02, 8.0, 480)


def fields(tag):
    if tag == "v1":
        f = v1.make_potential_funcs(**P1)
        Vv = v1.V_v(r, P1["bar_V_v"], P1["alpha"], P1["d_v"])
        Vs = v1.V_s(r, P1["bar_V_s"], P1["r_s"], P1["d_s"])
    elif tag == "v2":
        f = v2.make_potential_funcs(**P2)
        Vv = v2.V_v(r, P2["bar_V_v"], P2["alpha"], P2["d"])
        Vs = v2.V_s(r, P2["bar_V_s"], P2["r_s"])
    else:
        f = v3.make_potential_funcs(**P3)
        bar = 2 * M_Q - P3["bar_V_s"]
        Vv = v2.V_v(r, bar, P3["alpha"], P3["d"])
        Vs = v2.V_s(r, P3["bar_V_s"], P3["r_s"])
    VL = np.asarray(f["V_L"](r), float)
    VU = np.asarray(f["V_U"](r), float)
    den = M_Q + 0.5 * ET[tag]
    AL = 1.0 / (den - 0.5 * VL)
    AU = 1.0 / (den - 0.5 * VU)
    return np.asarray(Vv, float), np.asarray(Vs, float), VL, VU, AL, AU


def coords(x, y, step=4):
    return " ".join(f"({a:.4f},{b:.5f})" for a, b in zip(x[::step], y[::step]))


D = {t: fields(t) for t in ("v1", "v2", "v3")}
COL = {"v1": "blue!70!black", "v2": "red!70!black", "v3": "green!45!black"}
DASH = {"v1": "solid", "v2": "densely dashed", "v3": "dotted"}
NPAR = {"v1": 6, "v2": 5, "v3": 4}
THICK, THIN = "line width=1.05pt", "line width=0.45pt"

L = []
A = L.append
A("% Generated by make_potential_figure.py -- do not edit by hand.")
A(r"\begin{figure}[htbp]\centering")

# ---------------- shared variant key ----------------
A(r"\begin{tikzpicture}[baseline]")
x = 0.0
for t in ("v1", "v2", "v3"):
    A(rf"\draw[{COL[t]},{DASH[t]},line width=1.05pt] "
      rf"({x:.1f},0) -- ({x+0.62:.1f},0) "
      rf"node[right,inner sep=2pt,font=\small,black] "
      rf"{{{t}\,({NPAR[t]}\,par.)}};")
    x += 2.55
A(r"\end{tikzpicture}")
A(r"\\[2pt]")


def panel(title, ylabel, series, labels, ymin=None, ymax=None, extra=""):
    """series: list of (tag, yarray, width). labels: list of (x, y, text)."""
    A(r"\begin{tikzpicture}")
    A(r"\begin{axis}[width=0.47\textwidth,height=5.0cm,")
    A(r"  xlabel={$r$ [\si{\GeV^{-1}}]}, ylabel={" + ylabel + "},")
    lim = ""
    if ymin is not None:
        lim = f" ymin={ymin}, ymax={ymax},"
    A(f"  xmin=0, xmax=8,{lim} grid=both,")
    A(r"  every axis plot/.append style={line join=round},")
    A(r"  label style={font=\small}, tick label style={font=\scriptsize},")
    if extra:
        A(extra)
    A(r"  title style={font=\small}, title={" + title + "}]")
    for tag, y, w in series:
        A(rf"\addplot[{COL[tag]},{DASH[tag]},{w}] "
          rf"coordinates {{{coords(r, y)}}};")
    for lx, ly, txt in labels:
        A(rf"\node[font=\small,anchor=center] at (axis cs:{lx},{ly}) {{{txt}}};")
    A(r"\end{axis}")
    A(r"\end{tikzpicture}")


# ---------------- (a) V_v and V_s ----------------
panel(r"(a) $\Vv$ and $\Vs$", r"[\si{\GeV}]",
      [(t, D[t][0], THICK) for t in ("v1", "v2", "v3")]
      + [(t, D[t][1], THIN) for t in ("v1", "v2", "v3")],
      [(6.2, 1.80, r"$\Vv$"), (6.2, -0.80, r"$\Vs$")],
      ymin=-1.5, ymax=2.3)
A(r"\hfill")

# ---------------- (b) V_L and V_U ----------------
panel(r"(b) $\VL$ and $\VU$", r"[\si{\GeV}]",
      [(t, D[t][2], THICK) for t in ("v1", "v2", "v3")]
      + [(t, D[t][3], THIN) for t in ("v1", "v2", "v3")],
      [(6.2, 2.55, r"$\VL$"), (6.2, 0.15, r"$\VU$")],
      ymin=-1.5, ymax=3.1)

A(r"\\[6pt]")

# ---------------- (c) A_L and A_U ----------------
panel(r"(c) $\AL$ and $\AU$", r"[\si{\GeV^{-1}}]",
      [(t, D[t][4], THICK) for t in ("v1", "v2", "v3")]
      + [(t, D[t][5], THIN) for t in ("v1", "v2", "v3")],
      [(6.4, 0.565, r"$\AL$"), (6.4, 0.355, r"$\AU$")],
      ymin=0.27, ymax=0.60)
A(r"\hfill")

# ---------------- (d) tensor kernel ----------------
ker = {t: -(-D[t][0]) * D[t][1] * D[t][4] ** 2 * D[t][5] * 100.0
       for t in ("v1", "v2", "v3")}          # V_v^s = -V_v; in 10^-2 GeV^-1
panel(r"(d) $-\Vvs\Vs\AL^{2}\AU$", r"[$10^{-2}\,\si{\GeV^{-1}}$]",
      [(t, ker[t], THICK) for t in ("v1", "v2", "v3")],
      [], ymin=-8.8, ymax=0.9)

A(r"\caption{The fitted interactions of the three variants at the combined "
  r"best-fit parameters of Chapter~\ref{ch:results}. Colour and dash style "
  r"identify the variant; within each panel the thick curves are the first "
  r"quantity named and the thin ones the second, and both families are "
  r"labelled directly. "
  r"Panel~(a): the two fields. $\Vv$ rises towards $\bar V_v$ and $\Vs$ is "
  r"attractive; the three $\Vv$ agree closely over the region the wave "
  r"functions occupy, the three $\Vs$ do not. "
  r"Panel~(b): the combinations the reduction actually uses. $\VL$ lies above "
  r"$\VU$ everywhere, by $-2\Vs$, and the two merge as $\Vs\to0$. "
  r"Panel~(c): the reduction blocks at the self-consistent $\ET$ of the "
  r"$\state{1}{3}{S}{1}$ level. Here $\AL>\AU$ always, their difference being "
  r"$\AL\AU\Vs$ by Eq.~\eqref{eq:AU-minus-AL}; for v2 the two coincide beyond "
  r"$r\simeq\SI{2.5}{\GeV^{-1}}$, where its Gaussian scalar field has already "
  r"vanished. "
  r"Panel~(d): the radial kernel of the tensor force, "
  r"Eq.~\eqref{eq:F-minus-gL}. Being proportional to the product of the two "
  r"fields it is supported only where they overlap, and it is an order of "
  r"magnitude weaker in v2 than in v3.}")
A(r"\label{fig:potentials}")
A(r"\end{figure}")

open(OUT, "w").write("\n".join(L) + "\n")
print(f"wrote {OUT}")
for t in ("v1", "v2", "v3"):
    Vv, Vs, VL, VU, AL, AU = D[t]
    print(f"  {t}: A_L>A_U everywhere: {bool(np.all(AL > AU))}   "
          f"V_L>V_U everywhere: {bool(np.all(VL >= VU))}   "
          f"max|kernel| = {np.abs(ker[t]).max():.2f}e-2")
