"""Contour of chi^2 over (r_s, d_s) for v1/set A, other parameters fixed."""
import json, numpy as np
d = json.load(open("map.json"))
rs, ds, Z = np.array(d["r_s"]), np.array(d["d_s"]), np.array(d["chi2"])
cmin = float(np.nanmin(Z))
L = []
A = L.append
A("% Generated by make_chi2map_figure.py -- do not edit by hand.")
A(r"\begin{figure}[htbp]\centering")
A(r"\begin{tikzpicture}")
A(r"\begin{axis}[width=0.62\textwidth,height=6.2cm,")
A(r"  xlabel={$r_s$ [\si{\GeV^{-1}}]}, ylabel={$d_s$ [\si{\GeV^{-1}}]},")
A(r"  label style={font=\small}, tick label style={font=\scriptsize},")
A(r"  colorbar, colorbar style={font=\scriptsize,ylabel={$\chi^{2}-\chi^{2}_{\min}$}},")
A(r"  point meta min=0, point meta max=60,")
A(r"  view={0}{90},]")
A(r"\addplot3[surf,shader=interp,mesh/ordering=y varies,"
  rf"mesh/cols={len(rs)},mesh/rows={len(ds)}] coordinates {{")
for a, dv in enumerate(ds):
    row = " ".join(f"({rs[b]:.4f},{dv:.4f},{min(Z[a,b]-cmin,60.0):.4f})"
                   for b in range(len(rs)))
    A(row)
    A("")
A(r"};")
A(rf"\addplot[only marks,mark=*,mark size=1.6pt,white] "
  rf"coordinates {{({d['x'][4]:.4f},{d['x'][5]:.4f})}};")
A(r"\end{axis}")
A(r"\end{tikzpicture}")
A(r"\caption{$\chi^{2}$ over the $(r_s,d_s)$ plane for variant~v1 on set~A, "
  r"the other four parameters held at their best-fit values (white dot). The "
  r"colour scale is capped at $\chi^{2}-\chi^{2}_{\min}=60$; at "
  r"$r_s=\SI{2.5}{\GeV^{-1}}$ it already reaches $124$. This is a slice, not a "
  r"profile: it shows that the two scalar range parameters are not degenerate "
  r"\emph{with each other}, in agreement with their correlation of $-0.18$ in "
  r"Table~\ref{tab:correlations}, and therefore that the large uncertainty on "
  r"$r_s$ comes from its correlation with the vector-sector parameters.}")
A(r"\label{fig:chi2map}")
A(r"\end{figure}")
open("chi2map.tex", "w").write("\n".join(L) + "\n")
print("wrote chi2map.tex ; chi2_min on grid =", round(cmin, 3))
