"""Zoomed contour of chi^2 over (r_s, d_s) for v1/set A, other parameters fixed.

Reads map_zoom.json (produced by chi2map_zoom_scan.py) and writes chi2map.tex.
Contour lines at Delta chi^2 = 1, 4 and 9 are computed here with matplotlib
and written as `contour prepared` coordinates, so no gnuplot is needed.
"""
import json, numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

CAP = 30.0
# plotted window (the scan of map_zoom.json covers r_s in [0.3, 3], d_s in [1, 9])
RS_MAX, DS_MIN, DS_MAX = 2.2, 1.5, 7.5
d = json.load(open("map_zoom.json"))
rs, ds, Z = np.array(d["r_s"]), np.array(d["d_s"]), np.array(d["chi2"], float)
ir = rs <= RS_MAX + 1e-9
id_ = (ds >= DS_MIN - 1e-9) & (ds <= DS_MAX + 1e-9)
rs, ds, Z = rs[ir], ds[id_], Z[np.ix_(id_, ir)]
cmin = float(np.nanmin(Z))
D = Z - cmin
L = []
A = L.append
A("% Generated by make_chi2map_figure.py -- do not edit by hand.")
A(r"\begin{figure}[htbp]\centering")
A(r"\begin{tikzpicture}")
A(r"\begin{axis}[width=0.62\textwidth,height=7.2cm,")
A(r"  xlabel={$r_s$ [\si{\GeV^{-1}}]}, ylabel={$d_s$ [\si{\GeV^{-1}}]},")
A(r"  label style={font=\small}, tick label style={font=\scriptsize},")
A(r"  colorbar, colorbar style={font=\scriptsize,ylabel={$\chi^{2}-\chi^{2}_{\min}$}},")
A(rf"  point meta min=0, point meta max={CAP:.0f},")
A(rf"  xmin={rs.min():.3f}, xmax={rs.max():.3f}, ymin={ds.min():.3f}, ymax={ds.max():.3f},")
A(r"  view={0}{90},]")
A(r"\addplot3[surf,shader=interp,mesh/ordering=x varies,"
  rf"mesh/cols={len(rs)},mesh/rows={len(ds)}] coordinates {{")
for a, dv in enumerate(ds):
    row = " ".join(f"({rs[b]:.4f},{dv:.4f},{min(D[a,b],CAP):.4f})"
                   for b in range(len(rs)))
    A(row)
    A("")
A(r"};")
# contour lines
fig, ax = plt.subplots()
cs = ax.contour(rs, ds, D, levels=[1.0, 4.0, 9.0])
for lev, segs in zip(cs.levels, cs.allsegs):
    for seg in segs:
        if len(seg) < 3:
            continue
        A(rf"\addplot[white,thick,no marks,line width=0.6pt] coordinates {{")
        A(" ".join(f"({x:.4f},{y:.4f})" for x, y in seg))
        A(r"};")
A(rf"\addplot[only marks,mark=*,mark size=1.6pt,white] "
  rf"coordinates {{({d['x'][4]:.4f},{d['x'][5]:.4f})}};")
A(r"\end{axis}")
A(r"\end{tikzpicture}")
A(r"\caption{$\chi^{2}$ over the $(r_s,d_s)$ plane for variant~v1 on set~A, with "
  r"the other four parameters held at their best-fit values (white dot). The "
  r"white lines are the contours $\chi^{2}-\chi^{2}_{\min}=1$, $4$ and $9$, and "
  rf"the colour scale is limited to $\chi^{{2}}-\chi^{{2}}_{{\min}}={CAP:.0f}$. "
  r"Outside the plotted region, up to $r_s=\SI{12}{\GeV^{-1}}$, the difference "
  r"exceeds $60$ everywhere, and the scan covers $r_s$ up to \SI{3}{\GeV^{-1}} and $d_s$ from $1$ to \SI{9}{\GeV^{-1}}. The minimum lies in a narrow curved valley: across "
  r"the valley $\chi^{2}$ rises steeply, while along it $r_s$ and $d_s$ change "
  r"in opposite directions with a slow increase of $\chi^{2}$.}")
A(r"\label{fig:chi2map}")
A(r"\end{figure}")
open("chi2map.tex", "w").write("\n".join(L) + "\n")
print("wrote chi2map.tex ; chi2_min on grid =", round(cmin, 3),
      "; contour segments:", sum(len(s) for s in cs.allsegs))
