"""Figure for Sect. 9.4: HF(1S) and the P-wave singlet-triplet splitting as
functions of the vector regulator width d (variant v2, other parameters at the
combined best fit).  Data from discussion_studies.py hcd."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
D   = [2.5, 3.0, 3.28334, 3.75, 4.5, 5.5, 7.0]
HF  = [157.30, 109.61, 90.58, 67.63, 44.49, 27.50, 15.09]
HC  = [-89.06, -62.19, -50.77, -36.94, -23.37, -13.97, -7.49]
FIT = [("v1", 2.2252, 138.0, -72.4), ("v2", 3.2833, 90.6, -50.8),
       ("v3", 1.8916, 157.1, -79.2)]
c = lambda xs, ys: " ".join(f"({x:.4f},{y:.2f})" for x, y in zip(xs, ys))
L = ["% Generated by make_hf_figure.py -- do not edit by hand.",
     r"\begin{figure}[htbp]\centering", r"\begin{tikzpicture}",
     r"\begin{axis}[width=0.78\textwidth,height=6.4cm,",
     r"  xlabel={regularization width $d$ [\si{\GeV^{-1}}]},",
     r"  ylabel={mass difference [\si{\MeV}]}, xmin=1.6, xmax=7.4, ymin=-108, ymax=205,",
     r"  grid=both, label style={font=\small},",
     r"  tick label style={font=\scriptsize},",
     r"  legend style={font=\scriptsize,at={(0.5,-0.30)},anchor=north,"
     r"draw=none,legend columns=1,cells={anchor=west},"
     r"/tikz/every even column/.append style={column sep=10pt}},]",
     rf"\addplot[blue!70!black,thick] coordinates {{{c(D,HF)}}};",
     r"\addlegendentry{$\mathrm{HF}(1S)=M(J/\psi)-M(\eta_c)$, varying $d$ only}",
     rf"\addplot[red!70!black,thick,densely dashed] coordinates {{{c(D,HC)}}};",
     r"\addlegendentry{$M(h_c)-\langle M(\chi_{cJ})\rangle$, varying $d$ only}",
     r"\addplot[blue!70!black,only marks,mark=*,mark size=2pt] coordinates {"
     + " ".join(f"({d:.4f},{h:.2f})" for _, d, h, _ in FIT) + r"};",
     r"\addlegendentry{$\mathrm{HF}(1S)$ of the fitted variants v1, v2, v3}",
     r"\addplot[red!70!black,only marks,mark=square*,mark size=2pt] coordinates {"
     + " ".join(f"({d:.4f},{k:.2f})" for _, d, _, k in FIT) + r"};",
     r"\addlegendentry{$M(h_c)-\langle M(\chi_{cJ})\rangle$ of the fitted variants}",
     r"\addplot[black,dotted,thick] coordinates "
     r"{(1.6,112.81) (7.4,112.81)};",
     r"\addlegendentry{measured values: $+112.8$ and $0.00$~\si{\MeV}}",
     r"\addplot[black,dotted,thick,forget plot] coordinates "
     r"{(1.6,0) (7.4,0)};"]
for n, d, h, k in FIT:
    L.append(rf"\node[font=\tiny,anchor=south] at (axis cs:{d:.4f},{h+9:.2f}) "
             rf"{{{n}}};")
L += [r"\end{axis}", r"\end{tikzpicture}",
      r"\caption{The two hyperfine observables, $\mathrm{HF}(1S)$ and "
      r"$M(h_c)-\langle M(\chi_{cJ})\rangle$, as functions of the regularization width "
      r"$d$ of the vector potential of Table~\ref{tab:variants}, with the other "
      r"parameters held at the v2 combined best fit. Both fall by an order of magnitude "
      r"over the range shown, and the ratio "
      r"$[M(h_c)-\langle M(\chi_{cJ})\rangle]/\mathrm{HF}(1S)$ stays between $-0.57$ "
      r"and $-0.50$; this shows that the two observables are produced by the same term "
      r"of the interaction. The markers are the three fitted variants, each a separate "
      r"fit with its own values of the other parameters; they follow the same trend. "
      r"The dotted lines are the measured values, $+112.8$ and "
      r"$0.00\pm\SI{0.15}{\MeV}$: no single value of $d$ reproduces both.}",
      r"\label{fig:hf-vs-d}", r"\end{figure}"]
os.makedirs(os.path.join(HERE, "figures"), exist_ok=True)
open(os.path.join(HERE, "figures", "hf_vs_d.tex"), "w").write("\n".join(L) + "\n")
print("wrote figures/hf_vs_d.tex")
for i, d in enumerate(D):
    print(f"  d={d:6.3f}  HF={HF[i]:7.2f}  hc={HC[i]:7.2f}  ratio={HC[i]/HF[i]:+.3f}")
